version: "3"

services:
  app:
    image: node:12-alpine
    command: sh -c "npm i && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DB: database

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: database

volumes:
  mysql-data:
